name: RandomGift
version: 1.2.0
main: me.yourname.randomgift.RandomGiftPlugin
api-version: "1.21"
description: Gives a random item to a random online player every N minutes.

commands:
  randomgift:
    description: RandomGift admin command
    usage: /randomgift <reload|now|status|add|remove|list>
    aliases: [rg]

permissions:
  randomgift.use:
    default: op
  randomgift.reload:
    default: op
  randomgift.now:
    default: op
  randomgift.status:
    default: op
  randomgift.items:
    default: op
  randomgift.items.add:
    default: op
  randomgift.items.remove:
    default: op
  randomgift.items.list:
    default: op