name: RandomGift
version: 1.3.0
main: me.yourname.randomgift.RandomGiftPlugin
api-version: "1.21"
description: Gives a random item to a random online player every N minutes.

commands:
  randomgift:
    description: RandomGift admin command
    usage: /randomgift <reload|now|status|add|remove|list>
    aliases: [rg]

permissions:
  randomgift.use:
    description: Base permission to use /randomgift
    default: op

  randomgift.reload:
    description: Allows /randomgift reload
    default: op

  randomgift.now:
    description: Allows /randomgift now
    default: op

  randomgift.status:
    description: Allows /randomgift status
    default: op

  randomgift.items.add:
    description: Allows /randomgift add WHITELIST <MATERIAL>
    default: op

  randomgift.items.remove:
    description: Allows /randomgift remove WHITELIST <MATERIAL>
    default: op

  randomgift.items.list:
    description: Allows /randomgift list WHITELIST|POOL
    default: op
